### ISSUE TITLE
Humble pulling incompatible version

### ISSUE THREAD

**Issue by bartonp2** [ros2-gbp/robot_localization-release#1]
When installing robot_localization on Ubuntu focal with ROS humble version 3.5.0 is installed. However, this apparently has some issues on humble. When checking the robot_localization github I saw that humble is only supported up to 3.4.2 as seen here: https://github.com/cra-ros-pkg/robot_localization/tree/humble-devel

I tested and verified the behaviour in my project and think it would make sense to update the repo here accordingly.

**Comment by SteveMacenski** [comment]
It looks like I made an error filling in prompts while releasing to Humble and Rolling on the same day. Fixing shortly. 
https://github.com/ros/rosdistro/pull/37256

**Comment by bartonp2** [comment]
Great, thanks!On 17 May 2023 19:01, Steve Macenski ***@***.***> wrote:
It looks like I made an error filling in prompts while releasing to Humble and Rolling on the same day. Fixing shortly.
ros/rosdistro#37256
